// 手工异常模板：36 个“真正离谱”的模板 + 4 个确定性安全兜底。
// 永久后果全部在模板内冻结，DeepSeek 只负责文学表现。
import type {
  AbilityFamily,
  CharacterBeliefProposal,
  CommitmentProposal,
  RelationshipChangeProposal,
  ResultLevel,
  WorldEventProposal,
} from "../abilities/types.ts";
import type {
  ActivePlanProposal,
  FateAberrationTemplate,
  FateCondition,
  FateImmediateEffect,
  FateRecoveryHook,
  FateTwist,
  TemplateDelayedEffect,
} from "./types.ts";

const ALL_FAMILIES: AbilityFamily[] = [
  "perception",
  "divination",
  "concealment",
  "deception",
  "mental",
  "control",
  "mobility",
  "physical",
  "transformation",
  "protection",
  "binding",
  "curse",
  "ritual",
  "summoning",
  "tracking",
  "creation",
];

const SUCCESS_SIDE: ResultLevel[] = ["critical-success", "success", "partial-success"];
const FAILURE_SIDE: ResultLevel[] = ["failure", "fail-with-progress", "backlash"];

type TemplateInput = Omit<FateAberrationTemplate, "sourceType">;

function tpl(input: TemplateInput): FateAberrationTemplate {
  return { sourceType: "game-original-fate-template", ...input };
}

function worldEvent(title: string, detail: string, visibility: WorldEventProposal["visibility"] = "world"): WorldEventProposal {
  return { type: "fate-aberration", title, detail, participantIds: [], observerIds: [], visibility };
}

function belief(input: Omit<CharacterBeliefProposal, "claimType" | "truthStatus" | "confidence"> & Partial<Pick<CharacterBeliefProposal, "claimType" | "truthStatus" | "confidence">>): CharacterBeliefProposal {
  return { claimType: "report", truthStatus: "uncertain", confidence: 0.8, ...input };
}

function relationship(input: RelationshipChangeProposal): RelationshipChangeProposal {
  return input;
}

function commitment(input: CommitmentProposal): CommitmentProposal {
  return input;
}

function plan(input: ActivePlanProposal): ActivePlanProposal {
  return input;
}

function hook(input: FateRecoveryHook): FateRecoveryHook {
  return input;
}

function effect(kind: FateImmediateEffect["kind"], description: string, targetId?: string): FateImmediateEffect {
  return { kind, description, targetId };
}

function delayed(id: string, inWeeks: number, kind: TemplateDelayedEffect["kind"], description: string, worldEventTitle: string): TemplateDelayedEffect {
  return { id, inWeeks, kind, description, worldEventTitle };
}

function cond(kind: FateCondition["kind"], min?: number, max?: number): FateCondition {
  return { kind, min, max };
}

// ---------------------------------------------------------------- 纯离谱大成功
export const FATE_TEMPLATES: FateAberrationTemplate[] = [
  tpl({
    id: "fate-boon-bigger-secret",
    title: "目标之外还有更大的秘密",
    families: ["perception", "divination", "tracking"],
    primitives: ["REVEAL", "INFER", "TRACE"],
    polarity: "boon",
    twist: "pure",
    severity: 2,
    compatibleNormalResults: SUCCESS_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("absurd-opportunity", "原本的目标被找到，同时撞破了一个更大、更不该现在出现的秘密。"),
      effect("long-term-belief", "玩家因此相信某条公开结论是伪造的。"),
    ],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：更大的秘密浮出水面", "行动成功，但命运顺手掀开了更深一层帷幕。")],
    beliefProposals: [belief({ characterId: "player", subjectId: "bigger-secret", propositionKey: "fate:bigger-secret:exists", claim: "这条线索背后还有更大的秘密", secrecy: "restricted" })],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [plan({ title: "追查更大秘密", objective: "确认撞破的秘密属于谁、指向什么", currentStep: "从现场遗留物反推来源", ownerId: "player", participantIds: ["player"], secrecy: "restricted" })],
    narrativePremise: "本该到此为止的调查，却因为一次多余的回头，撞见了另一件正在发生的事。",
    narrativeConstraints: ["不得把新秘密写成普通道具", "新秘密必须是长期线索而非一次性信息"],
    recoveryHooks: [hook({ kind: "investigation", title: "追查更大秘密", objective: "把撞破的秘密查清或选择埋掉", detail: "可以长期经营，也可以主动放弃以降低风险。" })],
    absurdityScore: 4,
    longTermConsequenceScore: 4,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-boon-enemy-ranks",
    title: "伪装成功到被敌人当成高层",
    families: ["concealment", "deception"],
    primitives: ["CONCEAL", "DECEIVE"],
    polarity: "boon",
    twist: "pure",
    severity: 2,
    compatibleNormalResults: SUCCESS_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("misplaced-identity", "敌人把玩家当成组织干部，当场要求其主持一场行动。"),
      effect("organization-relation", "玩家被临时纳入敌方行动链。"),
    ],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：被当成自己人", "伪装好过头了，敌人开始向玩家布置任务。")],
    beliefProposals: [belief({ characterId: "enemy-contact", subjectId: "player-identity", propositionKey: "fate:player-identity:enemy-officer", claim: "这名陌生人是本部派来的干部", secrecy: "restricted" })],
    relationshipProposals: [relationship({ fromCharacterId: "enemy-contact", toCharacterId: "player", dimension: "respect", delta: 18, summary: "误以为玩家是上级干部" })],
    commitmentProposals: [],
    planProposals: [],
    narrativePremise: "对方不仅没有起疑，反而递过来一份只给“自己人”看的行动计划。",
    narrativeConstraints: ["不得让敌方无条件信任到交出全部秘密", "玩家必须选择如何接住这份错误信任"],
    recoveryHooks: [hook({ kind: "embrace", title: "将错就错或抽身", objective: "利用错误身份主持敌方行动，或找借口退出", detail: "错误身份本身就是可经营的资源。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 4,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-boon-internal-rift",
    title: "顺带撞见对方内讧",
    families: ["perception", "tracking", "protection", "mobility", "physical"],
    primitives: ["TRACE", "REVEAL", "DETECT"],
    polarity: "boon",
    twist: "pure",
    severity: 2,
    compatibleNormalResults: SUCCESS_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [effect("absurd-opportunity", "目标没怎么反抗，但目标所在的组织正在内讧，被玩家全程看见。")],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：撞见内讧现场", "行动成功，还免费看了一场对方组织的内部撕扯。")],
    beliefProposals: [belief({ characterId: "witness", subjectId: "internal-rift", propositionKey: "fate:rift:witness", claim: "我看见了对方组织正在内讧", secrecy: "restricted" })],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [plan({ title: "利用对方内讧", objective: "决定是否趁内讧撬动对方组织", currentStep: "确认内讧双方的身份", ownerId: "player", participantIds: ["player"], secrecy: "secret" })],
    narrativePremise: "门推开时，里面的人正在互相指控，没人注意到门缝里的眼睛。",
    narrativeConstraints: ["内讧必须当场可见且可被利用", "不得因此自动消灭对方组织"],
    recoveryHooks: [hook({ kind: "investigation", title: "利用内讧", objective: "把内讧变成组织可利用的裂缝", detail: "可以拉拢一方，也可以坐等事态发酵。" })],
    absurdityScore: 3,
    longTermConsequenceScore: 3,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-boon-debt-mistake",
    title: "对方误以为欠玩家一笔债",
    families: ["ritual", "protection"],
    primitives: ["RITUAL_EFFECT", "PROTECT"],
    polarity: "boon",
    twist: "pure",
    severity: 2,
    compatibleNormalResults: SUCCESS_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [effect("new-debt", "仪式成功，回应者把玩家误认为某位恩人，主动欠下一笔人情债。")],
    delayedEffects: [delayed("debt-return", 3, "new-debt", "欠债的一方派来信使，表示愿意兑现一个模糊承诺。", "命运：人情债上门")],
    worldEventProposals: [worldEvent("命运：错误的人情", "一位不该欠玩家的人，坚持认为玩家对他有恩。")],
    beliefProposals: [belief({ characterId: "mystery-benefactor", subjectId: "player-debt", propositionKey: "fate:debt:mistaken-benefactor", claim: "玩家曾救过我，我必须还这个人情", confidence: 0.9, secrecy: "restricted" })],
    relationshipProposals: [relationship({ fromCharacterId: "mystery-benefactor", toCharacterId: "player", dimension: "debt", delta: 25, summary: "误以为玩家是自己的恩人" })],
    commitmentProposals: [commitment({ type: "debt", participantIds: ["player", "mystery-benefactor"], summary: "神秘人物欠玩家一次模糊的人情", secrecy: "secret" })],
    planProposals: [],
    narrativePremise: "仪式对面的存在沉默片刻，然后以一种‘原来是你’的语气，郑重道谢。",
    narrativeConstraints: ["人情债必须来源错误但真实存在", "不得让对方因此无条件服从"],
    recoveryHooks: [hook({ kind: "commitment", title: "兑现或悬置人情", objective: "决定是否使用这笔错误的人情", detail: "人情是真实账目，用错场合会露馅。" })],
    absurdityScore: 4,
    longTermConsequenceScore: 4,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-boon-cat-omen",
    title: "被猫踩乱的牌正好指向答案",
    families: ["divination"],
    primitives: ["REVEAL", "INFER"],
    polarity: "boon",
    twist: "pure",
    severity: 1,
    compatibleNormalResults: SUCCESS_SIDE,
    prerequisites: [cond("rare-coincidence")],
    forbiddenConditions: [],
    immediateEffects: [
      effect("scene-absurdity", "一只猫踩乱了占卜牌阵，但乱牌拼出的方向恰好正确。"),
      effect("absurd-opportunity", "这套“猫踩牌”的巧合成为可重复使用、但没人敢保证的占卜谈资。"),
    ],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：猫的启示", "占卜被猫打断，结果却出奇地准。")],
    beliefProposals: [belief({ characterId: "player", subjectId: "cat-omen", propositionKey: "fate:cat:omen-trust", claim: "这只猫可能不简单", secrecy: "restricted" })],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [],
    narrativePremise: "猫从牌阵上走过，把牌踩得乱七八糟——可那些乱牌，竟拼出了正确方向。",
    narrativeConstraints: ["猫本身不能成为超自然存在", "巧合必须让玩家既相信又怀疑"],
    recoveryHooks: [hook({ kind: "rumor", title: "猫的传闻", objective: "选择相信巧合还是彻查猫的来历", detail: "一句传闻就能让这个巧合变成组织的谈资。" })],
    absurdityScore: 4,
    longTermConsequenceScore: 2,
    recoverabilityScore: 3,
  }),
  tpl({
    id: "fate-boon-wrong-ritual-correct-reply",
    title: "仪式回应了错误但相关的对象",
    families: ["ritual", "divination"],
    primitives: ["RITUAL_EFFECT", "INFER"],
    polarity: "boon",
    twist: "pure",
    severity: 1,
    compatibleNormalResults: SUCCESS_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [effect("misplaced-target", "仪式没有回应预期对象，却回应了一位与之紧密相关的存在，带来了更大线索。")],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：答非所问的正确", "回应者不是要找的人，却提供了要找的线索。")],
    beliefProposals: [belief({ characterId: "player", subjectId: "ritual-reply", propositionKey: "fate:ritual:wrong-right", claim: "回应者与目标存在未公开的联系", secrecy: "restricted" })],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [],
    narrativePremise: "烛火对面的声音完全不对，但他说出的第一句话，恰好是玩家最需要的那句。",
    narrativeConstraints: ["错误对象必须与目标相关", "不得因此省略原目标的后续调查"],
    recoveryHooks: [hook({ kind: "investigation", title: "追着错误对象查", objective: "从错误对象身上顺藤摸瓜", detail: "错误回应本身就成了新线索。" })],
    absurdityScore: 4,
    longTermConsequenceScore: 2,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-boon-godmother-letter",
    title: "收到灵界正式回函",
    families: ["ritual", "divination"],
    primitives: ["RITUAL_EFFECT", "REVEAL"],
    polarity: "boon",
    twist: "pure",
    severity: 3,
    compatibleNormalResults: SUCCESS_SIDE,
    prerequisites: [cond("large-ritual")],
    forbiddenConditions: [],
    immediateEffects: [
      effect("new-plan", "仪式收到一封署名模糊的灵界正式回函，附带一个远期邀请。"),
      effect("long-term-belief", "组织开始相信这封信来自某条被遗忘的传承。"),
    ],
    delayedEffects: [delayed("letter-followup", 4, "absurd-opportunity", "回函的第二页在数周后自行显形，露出一个地点。", "命运：回函的第二页")],
    worldEventProposals: [worldEvent("命运：灵界回函", "一封正式回函落在仪式桌上，落款被雾遮住。")],
    beliefProposals: [belief({ characterId: "player", subjectId: "spirit-letter", propositionKey: "fate:letter:real", claim: "回函来自一条被遗忘的传承", confidence: 0.7, secrecy: "secret" })],
    relationshipProposals: [],
    commitmentProposals: [commitment({ type: "agreement", participantIds: ["player", "spirit-correspondent"], summary: "灵界对应方希望玩家赴约", secrecy: "secret" })],
    planProposals: [plan({ title: "赴灵界之约", objective: "查清回函来历并决定是否赴约", currentStep: "破解落款上的雾", ownerId: "player", participantIds: ["player"], dueWeek: 4, secrecy: "secret" })],
    narrativePremise: "烟雾散尽后，桌上多了一封信。信纸是活的，还在等一个回答。",
    narrativeConstraints: ["回函必须来源不明但正式", "不得把信直接变成无敌道具"],
    recoveryHooks: [hook({ kind: "commitment", title: "赴约或回绝", objective: "决定是否回应灵界回函", detail: "回绝也是一种答案，但可能被记住。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 5,
    recoverabilityScore: 3,
  }),
  tpl({
    id: "fate-boon-famous-alias",
    title: "获得一个被追捧的离谱绰号",
    families: ["concealment", "mental"],
    primitives: ["CONCEAL", "INFLUENCE", "DECEIVE"],
    polarity: "boon",
    twist: "pure",
    severity: 2,
    compatibleNormalResults: SUCCESS_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("misplaced-identity", "玩家获得一个离谱但被追捧的绰号，陌生人开始主动示好。"),
      effect("mystic-signature", "绰号与某种神秘学特征绑定，辨识度极高。"),
    ],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：名声先于本人", "一个荒谬的绰号先于玩家本人传遍街巷。")],
    beliefProposals: [belief({ characterId: "public", subjectId: "player-alias", propositionKey: "fate:alias:famous", claim: "那位‘灰雾中的某某’就是这个人", confidence: 0.85, secrecy: "public" })],
    relationshipProposals: [relationship({ fromCharacterId: "public", toCharacterId: "player", dimension: "respect", delta: 14, summary: "被离谱绰号吸引来的敬意" })],
    commitmentProposals: [],
    planProposals: [],
    narrativePremise: "第二天，街上的孩子已经在用那个绰号玩闹——而它原本只是随口一说。",
    narrativeConstraints: ["绰号必须离谱但可被利用", "名声必须同时带来注视与麻烦"],
    recoveryHooks: [hook({ kind: "embrace", title: "经营绰号或甩掉它", objective: "决定是借名声办事还是澄清身份", detail: "名声会自己长大，放任不管也是选择。" })],
    absurdityScore: 4,
    longTermConsequenceScore: 4,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-boon-registered-owner",
    title: "封印物把组织登记为合法持有者",
    families: ["ritual", "creation", "summoning"],
    primitives: ["RITUAL_EFFECT", "TRANSFORM", "RESOURCE_CHANGE"],
    polarity: "boon",
    twist: "pure",
    severity: 4,
    compatibleNormalResults: SUCCESS_SIDE,
    prerequisites: [cond("large-ritual"), cond("high-pressure")],
    forbiddenConditions: [],
    immediateEffects: [
      effect("authority-misplacement", "某件封印物在仪式中把玩家组织登记为“合法持有者”，档案层面已成事实。"),
      effect("worldline-shift", "这件封印物的归属史被改写，世界线开始偏转。"),
    ],
    delayedEffects: [delayed("ownership-audit", 5, "organization-relation", "官方或教会在数周后开始核查新登记的持有者。", "命运：所有权核查")],
    worldEventProposals: [worldEvent("命运：被封印物选中", "封印物的登记名册上，赫然出现了玩家组织的名字。")],
    beliefProposals: [belief({ characterId: "church-auditor", subjectId: "org-ownership", propositionKey: "fate:ownership:registered", claim: "该组织确实持有这件封印物", confidence: 0.95, secrecy: "restricted" })],
    relationshipProposals: [relationship({ fromCharacterId: "church-auditor", toCharacterId: "player", dimension: "suspicion", delta: 20, summary: "对突然出现的合法持有者起疑" })],
    commitmentProposals: [],
    planProposals: [plan({ title: "应对所有权核查", objective: "决定是坐实持有者身份还是设法抹除登记", currentStep: "查清登记册的来源", ownerId: "player", participantIds: ["player"], secrecy: "secret" })],
    narrativePremise: "仪式结束后的名册上，墨迹自己挪动，把组织的名字写进了持有者一栏。",
    narrativeConstraints: ["必须写入世界线偏转记录", "所有权带来的是注视与责任，不是无敌"],
    recoveryHooks: [hook({ kind: "identity-claim", title: "坐实或抹除持有权", objective: "经营这份错误所有权，或付出代价抹掉它", detail: "两种选择都会留下长期痕迹。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 5,
    recoverabilityScore: 3,
  }),

  // ---------------------------------------------------------------- 诅咒式成功
  tpl({
    id: "fate-curse-seen-back",
    title: "看见目标的同时被目标看见",
    families: ["divination", "perception"],
    primitives: ["REVEAL", "INFER"],
    polarity: "disaster",
    twist: "cursed-boon",
    severity: 1,
    compatibleNormalResults: SUCCESS_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [effect("misplaced-audience", "占卜精确锁定了目标，目标也在同一瞬间反向看见了玩家。")],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：目光相接", "答案正确，代价是对方也看见了窥视者。")],
    beliefProposals: [belief({ characterId: "target", subjectId: "player-scry", propositionKey: "fate:scry:seen-back", claim: "有人在占卜我，我能认出那道目光", secrecy: "restricted" })],
    relationshipProposals: [relationship({ fromCharacterId: "target", toCharacterId: "player", dimension: "suspicion", delta: 18, summary: "被占卜时反向看见了玩家" })],
    commitmentProposals: [],
    planProposals: [],
    narrativePremise: "答案在纸上浮现的同时，纸上的眼睛也在看你。",
    narrativeConstraints: ["原占卜结果必须仍然正确", "被看见的代价必须真实且影响后续"],
    recoveryHooks: [hook({ kind: "cleanup", title: "处理目光残留", objective: "抹掉被看见的痕迹或主动示好", detail: "被看见不一定是敌人，但一定被记住了。" })],
    absurdityScore: 4,
    longTermConsequenceScore: 3,
    recoverabilityScore: 3,
  }),
  tpl({
    id: "fate-curse-identity-erased",
    title: "隐匿成功，法律身份却从档案消失",
    families: ["concealment", "protection"],
    primitives: ["CONCEAL", "PROTECT"],
    polarity: "disaster",
    twist: "cursed-boon",
    severity: 3,
    compatibleNormalResults: SUCCESS_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("misplaced-identity", "隐匿效果完美，连官方档案里的身份都被‘隐匿’掉了。"),
      effect("authority-misplacement", "玩家暂时失去法律身份：租房、行会、警局记录全部查无此人。"),
    ],
    delayedEffects: [delayed("identity-check", 2, "organization-relation", "警察厅开始核查一名查无此人的住户。", "命运：查无此人")],
    worldEventProposals: [worldEvent("命运：档案里没有你", "行动结束后，玩家发现自己从所有公共记录中消失了。")],
    beliefProposals: [belief({ characterId: "landlord", subjectId: "player-existence", propositionKey: "fate:identity:erased", claim: "这间房里好像从没有人住过", confidence: 0.7, secrecy: "restricted" })],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [plan({ title: "找回法律身份", objective: "让档案重新认识自己", currentStep: "寻找能证明身份的人证与物证", ownerId: "player", participantIds: ["player"], secrecy: "secret" })],
    narrativePremise: "回到住处时，房东正站在门口，问“你是谁”。",
    narrativeConstraints: ["原隐匿必须成功", "身份消失必须可恢复，不能永久死档"],
    recoveryHooks: [hook({ kind: "identity-claim", title: "重新登记身份", objective: "用证人或物件把身份找回来", detail: "找回身份的过程本身就是一段长期任务。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 5,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-curse-teleport-under-table",
    title: "传送成功，落点是敌方会议桌下",
    families: ["mobility", "physical"],
    primitives: ["MOVE"],
    polarity: "disaster",
    twist: "cursed-boon",
    severity: 1,
    compatibleNormalResults: SUCCESS_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [effect("misplaced-location", "传送精确成功——精确地落进敌方会议桌下面。")],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：桌下的来客", "传送落点正好是敌方会议桌下方。")],
    beliefProposals: [],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [],
    narrativePremise: "脚下的灵性光辉散去，头顶是皮鞋与整张会议桌的重量。",
    narrativeConstraints: ["玩家必须有机会自救", "敌方不能因此无条件发现玩家"],
    recoveryHooks: [hook({ kind: "cleanup", title: "桌下脱身", objective: "在会议结束前找机会离开或听完全程", detail: "最危险的位置往往也是最安全的情报位。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 2,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-curse-control-mistaken-boss",
    title: "控制成功，旁观者误以为玩家是高层",
    families: ["control", "mental"],
    primitives: ["CONTROL", "INFLUENCE"],
    polarity: "disaster",
    twist: "cursed-boon",
    severity: 2,
    compatibleNormalResults: SUCCESS_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("misplaced-audience", "目标被控制住了，但旁观者全都误以为玩家是某组织高层。"),
      effect("organization-relation", "一份错误的上下级关系开始在旁观者中传播。"),
    ],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：被误认的上级", "控制成功，围观者却对玩家行了个不该行的礼。")],
    beliefProposals: [belief({ characterId: "bystander", subjectId: "player-rank", propositionKey: "fate:rank:mistaken", claim: "这位是那家组织的高层", secrecy: "restricted" })],
    relationshipProposals: [relationship({ fromCharacterId: "bystander", toCharacterId: "player", dimension: "fear", delta: 16, summary: "误以为玩家是高层的恐惧" })],
    commitmentProposals: [],
    planProposals: [],
    narrativePremise: "目标僵在原地，而旁边的侍者已经在对玩家鞠躬，称呼一个从未听过的头衔。",
    narrativeConstraints: ["原控制必须成功", "误认必须带来具体社交后果"],
    recoveryHooks: [hook({ kind: "rumor", title: "澄清或冒名", objective: "决定是否利用这个错误头衔", detail: "头衔会自己传播，越晚澄清越难。" })],
    absurdityScore: 4,
    longTermConsequenceScore: 3,
    recoverabilityScore: 3,
  }),
  tpl({
    id: "fate-curse-materials-breed",
    title: "材料没有消耗，反而开始自行繁殖",
    families: ["ritual", "creation"],
    primitives: ["RITUAL_EFFECT", "RESOURCE_CHANGE", "TRANSFORM"],
    polarity: "disaster",
    twist: "cursed-boon",
    severity: 3,
    compatibleNormalResults: SUCCESS_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("resource-phenomenon", "仪式材料没有消耗，反而多出一倍，并且仍在缓慢增殖。"),
      effect("organization-relation", "增殖的材料引来了黑市与教会的共同注意。"),
    ],
    delayedEffects: [delayed("breeding-surge", 2, "resource-phenomenon", "储藏室里的材料一夜之间多到溢出。", "命运：增殖失控")],
    worldEventProposals: [worldEvent("命运：会繁殖的材料", "仪式桌上的材料没变少，反而多了一份。")],
    beliefProposals: [belief({ characterId: "church-watcher", subjectId: "breeding-materials", propositionKey: "fate:materials:breeding", claim: "有人在批量制造非凡材料", secrecy: "restricted" })],
    relationshipProposals: [],
    commitmentProposals: [commitment({ type: "debt", participantIds: ["player", "blackmarket"], summary: "黑市商人想收购这批材料", secrecy: "restricted" })],
    planProposals: [plan({ title: "处理增殖材料", objective: "卖出、销毁或封存会繁殖的材料", currentStep: "评估材料的危险等级", ownerId: "player", participantIds: ["player"], secrecy: "secret" })],
    narrativePremise: "仪式结束后，桌上的材料非但没少，还多出了一份，边缘仍在缓慢生长。",
    narrativeConstraints: ["增殖必须有上限或可处理手段", "必须引来外部注视"],
    recoveryHooks: [hook({ kind: "cleanup", title: "处理增殖材料", objective: "封存、卖出或销毁材料", detail: "每种处理方式都会带来不同的后续。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 4,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-curse-hat-invisible",
    title: "隐匿成功，帽子没有被隐匿",
    families: ["concealment"],
    primitives: ["CONCEAL"],
    polarity: "disaster",
    twist: "cursed-boon",
    severity: 1,
    compatibleNormalResults: SUCCESS_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [effect("misplaced-item", "隐匿效果完美，但玩家的帽子仍孤零零地悬在半空。")],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：悬空的帽子", "街上所有人都看见一顶帽子在走路。")],
    beliefProposals: [],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [],
    narrativePremise: "所有人都在看那顶帽子——没人看见帽子下面的人，这才是问题。",
    narrativeConstraints: ["帽子必须成为唯一线索", "必须给玩家拿走帽子的机会"],
    recoveryHooks: [hook({ kind: "cleanup", title: "收回帽子", objective: "在更多人注意到之前把帽子拿回来", detail: "一顶帽子也能变成身份线索。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 2,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-curse-literal-order",
    title: "目标严格执行命令的字面含义",
    families: ["mental", "control"],
    primitives: ["INFLUENCE", "CONTROL"],
    polarity: "disaster",
    twist: "cursed-boon",
    severity: 2,
    compatibleNormalResults: SUCCESS_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("misinterpreted-answer", "暗示成功，但目标把每句话都按最荒谬的字面意思执行。"),
      effect("organization-relation", "目标的离谱举动让某个组织开始追查玩家。"),
    ],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：字面执行", "目标完全服从了命令——以最不该服从的方式。")],
    beliefProposals: [belief({ characterId: "target", subjectId: "player-order", propositionKey: "fate:order:literal", claim: "命令就是要我这样做", confidence: 0.9, secrecy: "restricted" })],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [],
    narrativePremise: "目标点头答应，然后转身做出了那件谁都不会想到会去做的事。",
    narrativeConstraints: ["原暗示必须成功", "字面执行的后果必须可控可收场"],
    recoveryHooks: [hook({ kind: "cleanup", title: "收拾字面后果", objective: "在事态扩大前修正目标的离谱行为", detail: "越解释，目标越觉得玩家在考验自己。" })],
    absurdityScore: 4,
    longTermConsequenceScore: 3,
    recoverabilityScore: 3,
  }),
  tpl({
    id: "fate-curse-trail-pattern",
    title: "逃跑轨迹成为敌人长期识别的图案",
    families: ["mobility", "tracking", "physical"],
    primitives: ["MOVE", "TRACE"],
    polarity: "disaster",
    twist: "cursed-boon",
    severity: 3,
    compatibleNormalResults: SUCCESS_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("mystic-signature", "逃跑轨迹在空中留下一个清晰的仪式图案，被敌人拓印下来。"),
      effect("long-term-belief", "敌方神秘学顾问坚信这是某个古老教派的标记。"),
    ],
    delayedEffects: [delayed("pattern-hunt", 1, "organization-relation", "敌人开始在城中搜索符合该图案特征的行动者。", "命运：图案通缉")],
    worldEventProposals: [worldEvent("命运：会说话的轨迹", "逃跑路线留下的图案被敌人当作重要证据。")],
    beliefProposals: [belief({ characterId: "enemy-occultist", subjectId: "trail-pattern", propositionKey: "fate:pattern:cult", claim: "这是某个古老教派的行动标记", confidence: 0.85, secrecy: "restricted" })],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [plan({ title: "摆脱图案标记", objective: "让敌人不再把图案与玩家关联", currentStep: "找出图案被拓印的渠道", ownerId: "player", participantIds: ["player"], secrecy: "secret" })],
    narrativePremise: "追兵停下脚步，不是因为追丢，而是因为脚下的轨迹让他们集体愣住了。",
    narrativeConstraints: ["图案必须长期可被识别", "必须存在摆脱标记的路径"],
    recoveryHooks: [hook({ kind: "cleanup", title: "抹掉标记", objective: "用误导性行动冲淡图案的独特性", detail: "也可以反过来利用敌人的误解。" })],
    absurdityScore: 4,
    longTermConsequenceScore: 5,
    recoverabilityScore: 3,
  }),
  tpl({
    id: "fate-curse-name-on-list",
    title: "仪式成功，名字却进了禁忌名单",
    families: ["ritual", "curse"],
    primitives: ["RITUAL_EFFECT", "BIND", "RESOURCE_CHANGE"],
    polarity: "disaster",
    twist: "cursed-boon",
    severity: 4,
    compatibleNormalResults: SUCCESS_SIDE,
    prerequisites: [cond("large-ritual"), cond("high-pressure")],
    forbiddenConditions: [],
    immediateEffects: [
      effect("authority-misplacement", "仪式圆满完成，但玩家的名字出现在一份禁忌名单上，落款是一方不该认识他的势力。"),
      effect("worldline-shift", "该势力提前开始关注贝克兰德，世界线偏转。"),
    ],
    delayedEffects: [delayed("list-audit", 3, "organization-relation", "名单的持有者开始核实玩家身份。", "命运：名单核实")],
    worldEventProposals: [worldEvent("命运：名字上榜", "一份本不该出现的名单，写上了玩家的名字。")],
    beliefProposals: [belief({ characterId: "list-holder", subjectId: "player-name", propositionKey: "fate:list:player", claim: "这个名字值得提前注意", confidence: 0.9, secrecy: "secret" })],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [plan({ title: "应对名单注视", objective: "查清名单来源并决定如何应对注视", currentStep: "追查名单的传递链", ownerId: "player", participantIds: ["player"], secrecy: "secret" })],
    narrativePremise: "仪式成功的那一刻，远方某支笔在纸上停了一下，写下一个名字。",
    narrativeConstraints: ["必须写入世界线偏转记录", "注视必须留出经营与周旋空间"],
    recoveryHooks: [hook({ kind: "bargain", title: "与注视周旋", objective: "用情报、伪装或交易应付提前到来的目光", detail: "被提前注意不是死局，而是更早的棋局。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 5,
    recoverabilityScore: 3,
  }),

  // ---------------------------------------------------------------- 歪打正着
  tpl({
    id: "fate-luck-traced-mole",
    title: "没追到目标，却追到了组织内鬼",
    families: ["tracking", "perception"],
    primitives: ["TRACE", "REVEAL"],
    polarity: "boon",
    twist: "fortunate-disaster",
    severity: 2,
    compatibleNormalResults: FAILURE_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("misplaced-target", "原目标跟丢了，但足迹把玩家引向组织内部的内鬼。"),
      effect("new-plan", "玩家获得一次清理门户的机会。"),
    ],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：追丢了狼，追到了狐狸", "追踪失败，却撞见一个更不该出现的人。")],
    beliefProposals: [belief({ characterId: "player", subjectId: "org-mole", propositionKey: "fate:mole:exists", claim: "组织里有内鬼，且与目标有交集", confidence: 0.8, secrecy: "secret" })],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [plan({ title: "清理内鬼", objective: "确认内鬼身份并决定处置方式", currentStep: "布设诱饵验证内鬼", ownerId: "player", participantIds: ["player"], secrecy: "secret" })],
    narrativePremise: "足迹在第三个路口断了——却在断口处，露出了另一双更熟悉的鞋印。",
    narrativeConstraints: ["原追踪必须失败", "内鬼身份必须仍需验证，不能自动实锤"],
    recoveryHooks: [hook({ kind: "investigation", title: "清理门户", objective: "在打草惊蛇前确认内鬼身份", detail: "错误指认会毁掉组织信任。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 5,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-luck-wrong-ritual-receipt",
    title: "仪式失败，却收到另一位存在的正式回函",
    families: ["ritual"],
    primitives: ["RITUAL_EFFECT"],
    polarity: "boon",
    twist: "fortunate-disaster",
    severity: 3,
    compatibleNormalResults: FAILURE_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("misplaced-target", "预期对象没有回应，但另一位存在送来了正式回函。"),
      effect("absurd-opportunity", "回函附带了更大的线索与一次合作邀请。"),
    ],
    delayedEffects: [delayed("receipt-followup", 2, "absurd-opportunity", "回函附带的地点显形，邀请玩家前往。", "命运：回函邀约")],
    worldEventProposals: [worldEvent("命运：答错的人答对了", "仪式失败，桌上的回函却来自另一个名字。")],
    beliefProposals: [belief({ characterId: "player", subjectId: "wrong-recipient", propositionKey: "fate:ritual:other-recipient", claim: "回函者与目标存在关联", confidence: 0.75, secrecy: "secret" })],
    relationshipProposals: [],
    commitmentProposals: [commitment({ type: "agreement", participantIds: ["player", "unknown-recipient"], summary: "未知存在邀请玩家赴约", secrecy: "secret" })],
    planProposals: [plan({ title: "赴未知之约", objective: "查清回函者身份并决定是否赴约", currentStep: "破解回函上的暗记", ownerId: "player", participantIds: ["player"], secrecy: "secret" })],
    narrativePremise: "仪式没有任何回应，直到玩家准备收拾桌面——信已经躺在那里，落款陌生。",
    narrativeConstraints: ["原仪式必须失败", "回函者身份必须保持神秘可查"],
    recoveryHooks: [hook({ kind: "commitment", title: "赴约或搁置", objective: "决定如何处理这封错误但重要的回函", detail: "搁置太久，回函可能自己来敲门。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 5,
    recoverabilityScore: 3,
  }),
  tpl({
    id: "fate-luck-police-superior",
    title: "催眠失败，警察却把玩家当成直属上级",
    families: ["mental", "deception"],
    primitives: ["INFLUENCE", "DECEIVE"],
    polarity: "boon",
    twist: "fortunate-disaster",
    severity: 2,
    compatibleNormalResults: FAILURE_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("misplaced-audience", "目标没有服从，但旁边的警察忽然把玩家当成直属上级。"),
      effect("misplaced-identity", "警察开始向玩家汇报本不该汇报的案件。"),
    ],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：认错上司", "催眠落空，警察却立正敬礼。")],
    beliefProposals: [belief({ characterId: "police-officer", subjectId: "player-rank", propositionKey: "fate:police:superior", claim: "这位是局里的高级探员", confidence: 0.9, secrecy: "restricted" })],
    relationshipProposals: [relationship({ fromCharacterId: "police-officer", toCharacterId: "player", dimension: "respect", delta: 15, summary: "误以为玩家是上级" })],
    commitmentProposals: [],
    planProposals: [],
    narrativePremise: "目标毫无反应，旁边的警察却忽然敬礼，开口就是‘长官，正想向您汇报’。",
    narrativeConstraints: ["原催眠必须失败", "错误信任必须可能被拆穿"],
    recoveryHooks: [hook({ kind: "embrace", title: "借用错误身份", objective: "在穿帮前用好警察的信任", detail: "每多问一句，穿帮风险就高一分。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 3,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-luck-divination-tamperer",
    title: "占卜错误，却暴露了有人正在篡改占卜",
    families: ["divination"],
    primitives: ["REVEAL", "INFER"],
    polarity: "boon",
    twist: "fortunate-disaster",
    severity: 3,
    compatibleNormalResults: FAILURE_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("absurd-opportunity", "占卜结果全错，但错法本身暴露了有人正系统性地篡改占卜。"),
      effect("long-term-belief", "玩家确认占卜网络已被污染。"),
    ],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：被污染的水面", "占卜失败，却照出了水下的手。")],
    beliefProposals: [belief({ characterId: "player", subjectId: "divination-tampering", propositionKey: "fate:divination:tampered", claim: "有人在系统篡改占卜结果", confidence: 0.85, secrecy: "secret" })],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [plan({ title: "追查篡改者", objective: "找出谁在污染占卜网络", currentStep: "用无法被篡改的媒介反向定位", ownerId: "player", participantIds: ["player"], secrecy: "secret" })],
    narrativePremise: "答案错得离谱，但错的方向完全一致——仿佛所有牌都在被同一只手拨弄。",
    narrativeConstraints: ["原占卜必须失败", "篡改线索必须指向可追查的实体"],
    recoveryHooks: [hook({ kind: "investigation", title: "追查篡改者", objective: "定位并处理占卜污染源", detail: "这比原目标更大，也更重要。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 5,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-luck-wrong-cellar",
    title: "找错房间，却撞见了正确的密门",
    families: ["perception", "mobility"],
    primitives: ["DETECT", "REVEAL", "MOVE"],
    polarity: "boon",
    twist: "fortunate-disaster",
    severity: 1,
    compatibleNormalResults: FAILURE_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [effect("misplaced-location", "找错了地窖，却在一面错误的墙上摸到了正确的密门。")],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：错门后的正门", "走错房间，反而摸到了密门。")],
    beliefProposals: [],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [],
    narrativePremise: "门后只有酒桶和灰尘——直到玩家的手在错误的位置按到了不该有的缝隙。",
    narrativeConstraints: ["密门必须真实且可继续调查", "不能因此直接完成原目标"],
    recoveryHooks: [hook({ kind: "investigation", title: "探索密门", objective: "查清密门通向哪里", detail: "密门可能比原目标更有价值。" })],
    absurdityScore: 4,
    longTermConsequenceScore: 2,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-luck-chase-sent-away",
    title: "没逃出去，却把追兵送走",
    families: ["mobility", "physical"],
    primitives: ["MOVE", "CONCEAL"],
    polarity: "boon",
    twist: "fortunate-disaster",
    severity: 1,
    compatibleNormalResults: FAILURE_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [effect("misplaced-target", "逃脱失败，但命运把追兵引向了完全相反的方向。")],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：追兵追错了人", "玩家没逃掉，追兵却跑了。")],
    beliefProposals: [],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [],
    narrativePremise: "巷子尽头是死路，追兵却在最后一刻拐进了另一条巷子，追着一个影子跑远了。",
    narrativeConstraints: ["逃脱本身必须失败", "追兵离开必须留下解释空间（影子/噪音/替身）"],
    recoveryHooks: [hook({ kind: "cleanup", title: "趁乱离开", objective: "在追兵发现追错前离开现场", detail: "窗口期有限，但真实存在。" })],
    absurdityScore: 4,
    longTermConsequenceScore: 2,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-luck-rumor-cover",
    title: "伪装失败，反而传出更有利的谣言",
    families: ["concealment", "deception"],
    primitives: ["CONCEAL", "DECEIVE"],
    polarity: "boon",
    twist: "fortunate-disaster",
    severity: 2,
    compatibleNormalResults: FAILURE_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("organization-relation", "伪装当场穿帮，但穿帮方式催生了更有利的谣言。"),
      effect("long-term-belief", "街巷开始相信玩家是某位大人物的代理人。"),
    ],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：穿帮的掩护", "假身份被拆穿，真谣言却立了起来。")],
    beliefProposals: [belief({ characterId: "public", subjectId: "player-rumor", propositionKey: "fate:rumor:agent", claim: "那位是某位大人物的代理人", confidence: 0.8, secrecy: "public" })],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [],
    narrativePremise: "谎话被当面戳穿，可酒馆里的人已经开始传‘他其实是替那位办事的’。",
    narrativeConstraints: ["原伪装必须失败", "谣言必须双刃：更有利也更危险"],
    recoveryHooks: [hook({ kind: "rumor", title: "经营谣言", objective: "决定是借谣言办事还是澄清", detail: "谣言会自动成长。" })],
    absurdityScore: 4,
    longTermConsequenceScore: 3,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-luck-item-mixup",
    title: "控制失败，目标却把关键物品交给玩家",
    families: ["control", "mental"],
    primitives: ["CONTROL", "INFLUENCE"],
    polarity: "boon",
    twist: "fortunate-disaster",
    severity: 2,
    compatibleNormalResults: FAILURE_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("misplaced-item", "控制完全失败，但目标误把玩家当成接头人，主动交出关键物品。"),
      effect("new-debt", "目标事后一定会追讨这件物品。"),
    ],
    delayedEffects: [delayed("item-demand", 2, "new-debt", "目标开始追查交接失误。", "命运：追讨交接物")],
    worldEventProposals: [worldEvent("命运：交错了人", "目标把关键物品塞进玩家手里，转身离开。")],
    beliefProposals: [belief({ characterId: "target", subjectId: "player-identity", propositionKey: "fate:mixup:contact", claim: "他就是接头人", confidence: 0.95, secrecy: "restricted" })],
    relationshipProposals: [],
    commitmentProposals: [commitment({ type: "exchange", participantIds: ["player", "target"], summary: "目标以为完成了一次交接", secrecy: "restricted" })],
    planProposals: [],
    narrativePremise: "控制失效的瞬间，目标却像见到老熟人一样，把东西塞进玩家手里。",
    narrativeConstraints: ["原控制必须失败", "物品必须真实且带来后续追讨"],
    recoveryHooks: [hook({ kind: "bargain", title: "处理交接物", objective: "决定是归还、私吞还是借此接触目标", detail: "物品就是一张错误但真实的入场券。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 4,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-luck-historical-echo",
    title: "错误历史投影短暂进入当前时代",
    families: ["ritual", "divination"],
    primitives: ["RITUAL_EFFECT", "TRANSFORM"],
    polarity: "boon",
    twist: "fortunate-disaster",
    severity: 4,
    compatibleNormalResults: FAILURE_SIDE,
    prerequisites: [cond("large-ritual"), cond("high-pressure")],
    forbiddenConditions: [],
    immediateEffects: [
      effect("misplaced-time", "仪式失败，却让一段错误的历史投影短暂进入当前时代。"),
      effect("worldline-shift", "投影留下的实物证据开始改写人们对历史的认知。"),
    ],
    delayedEffects: [delayed("echo-residue", 3, "worldline-shift", "历史投影的残留物被找到，引发争抢。", "命运：投影残迹")],
    worldEventProposals: [worldEvent("命运：历史的影子", "一段不属于这个时代的历史，在仪式失败处停留了片刻。")],
    beliefProposals: [belief({ characterId: "player", subjectId: "history-echo", propositionKey: "fate:echo:real", claim: "那段历史投影可能是真的", confidence: 0.7, secrecy: "secret" })],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [plan({ title: "追查历史投影", objective: "弄清投影来自哪段历史、为何出现", currentStep: "收集投影留下的残留物", ownerId: "player", participantIds: ["player"], secrecy: "secret" })],
    narrativePremise: "失败的仪式没有造成爆炸——而是让空气里短暂浮现了一座不该存在的旧城一角。",
    narrativeConstraints: ["必须写入世界线偏转记录", "投影必须留下可调查的残留物"],
    recoveryHooks: [hook({ kind: "investigation", title: "追查投影", objective: "弄清历史投影的来历", detail: "投影留下的东西会成为多方争抢的线索。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 5,
    recoverabilityScore: 3,
  }),

  // ---------------------------------------------------------------- 全面失控
  tpl({
    id: "fate-disaster-self-registered",
    title: "仪式把玩家自己登记成追踪目标",
    families: ["tracking", "divination", "protection", "physical", "perception"],
    primitives: ["TRACE", "REVEAL", "DETECT"],
    polarity: "disaster",
    twist: "full-disaster",
    severity: 3,
    compatibleNormalResults: FAILURE_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("misplaced-target", "追踪失败，登记簿上却出现了玩家自己的名字与特征。"),
      effect("authority-misplacement", "某方势力开始把玩家当作被追缉对象。"),
    ],
    delayedEffects: [delayed("hunt-begin", 1, "organization-relation", "被登记的特征开始在悬赏渠道流传。", "命运：悬赏令")],
    worldEventProposals: [worldEvent("命运：自己上了名单", "仪式失败，登记簿上的名字却是玩家自己。")],
    beliefProposals: [belief({ characterId: "hunter", subjectId: "player-wanted", propositionKey: "fate:self-registered:wanted", claim: "这名目标正在城内活动", confidence: 0.9, secrecy: "restricted" })],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [plan({ title: "从名单上消失", objective: "抹掉登记或伪造另一条线索", currentStep: "查清登记簿流向", ownerId: "player", participantIds: ["player"], secrecy: "secret" })],
    narrativePremise: "仪式没有找到目标，却把玩家自己的画像写进了追踪登记。",
    narrativeConstraints: ["原追踪必须失败", "悬赏必须可撤销或可误导"],
    recoveryHooks: [hook({ kind: "cleanup", title: "从名单上消失", objective: "抹掉错误登记或转移追缉方向", detail: "被追缉也是一种可经营的局面。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 4,
    recoverabilityScore: 3,
  }),
  tpl({
    id: "fate-disaster-wanted-mixup",
    title: "伪装失效，却被档案认定为另一名通缉犯",
    families: ["concealment", "deception"],
    primitives: ["CONCEAL", "DECEIVE"],
    polarity: "disaster",
    twist: "full-disaster",
    severity: 3,
    compatibleNormalResults: FAILURE_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("misplaced-identity", "伪装当场失效，目击者却把玩家认成另一名通缉犯。"),
      effect("organization-relation", "警察厅开始按通缉令追捕玩家。"),
    ],
    delayedEffects: [delayed("wanted-posters", 1, "organization-relation", "通缉令出现在玩家常去的街区。", "命运：通缉令上墙")],
    worldEventProposals: [worldEvent("命运：认错通缉犯", "伪装失败，玩家被当成另一个更值钱的人。")],
    beliefProposals: [belief({ characterId: "police", subjectId: "player-identity", propositionKey: "fate:wanted:identity", claim: "他就是那名通缉犯", confidence: 0.92, secrecy: "public" })],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [plan({ title: "洗清错误通缉", objective: "证明玩家不是那名通缉犯", currentStep: "寻找真正的通缉犯行踪", ownerId: "player", participantIds: ["player"], secrecy: "secret" })],
    narrativePremise: "面纱滑落的瞬间，围观者反而兴奋起来——‘是他！悬赏单上那个！’",
    narrativeConstraints: ["原伪装必须失败", "通缉必须可洗清或可利用"],
    recoveryHooks: [hook({ kind: "identity-claim", title: "洗清通缉", objective: "用证据或替身证明身份", detail: "错误的通缉令也可能反向钓出真正的通缉犯。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 4,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-disaster-brought-thing-back",
    title: "灵界旅行失败，带回一个不该出现的东西",
    families: ["mobility", "summoning", "physical"],
    primitives: ["MOVE", "SUMMON"],
    polarity: "disaster",
    twist: "full-disaster",
    severity: 3,
    compatibleNormalResults: FAILURE_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("misplaced-location", "灵界旅行失败，玩家回到办公室时身后跟着一个不该出现的东西。"),
      effect("new-debt", "这个东西要求玩家为带它回来支付代价。"),
    ],
    delayedEffects: [delayed("thing-settles", 1, "new-debt", "被带回的东西开始占据办公室一角。", "命运：不速之客")],
    worldEventProposals: [worldEvent("命运：带回来的东西", "办公室的门关上后，多了一个不该存在的影子。")],
    beliefProposals: [belief({ characterId: "player", subjectId: "brought-thing", propositionKey: "fate:brought:real", claim: "它是跟着我回来的", secrecy: "secret" })],
    relationshipProposals: [],
    commitmentProposals: [commitment({ type: "debt", participantIds: ["player", "brought-thing"], summary: "带回灵界之物所欠的代价", secrecy: "secret" })],
    planProposals: [plan({ title: "送走不速之客", objective: "弄清它是什么并把它送回去", currentStep: "确认它对什么有反应", ownerId: "player", participantIds: ["player"], secrecy: "secret" })],
    narrativePremise: "传送的灵光散尽，办公室的门在身后关上——房间里多了一个影子。",
    narrativeConstraints: ["原旅行必须失败", "被带回的东西必须可沟通或可送走"],
    recoveryHooks: [hook({ kind: "bargain", title: "与不速之客谈判", objective: "弄清它想要什么，把它送回去", detail: "它可能带来麻烦，也可能带来情报。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 5,
    recoverabilityScore: 3,
  }),
  tpl({
    id: "fate-disaster-hypnosis-bounce",
    title: "催眠反弹，施术者相信了自己的谎言",
    families: ["mental"],
    primitives: ["INFLUENCE", "CONTROL"],
    polarity: "disaster",
    twist: "full-disaster",
    severity: 1,
    compatibleNormalResults: FAILURE_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("misplaced-audience", "催眠没有生效，施术者却短暂相信了自己编造的谎言。"),
      effect("long-term-belief", "谎言开始影响玩家自己的判断。"),
    ],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：谎言的回声", "催眠落空，说谎的人先信了。")],
    beliefProposals: [belief({ characterId: "player", subjectId: "self-lie", propositionKey: "fate:hypnosis:self", claim: "自己刚才编造的版本可能是真的", confidence: 0.65, secrecy: "restricted" })],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [],
    narrativePremise: "对方的眼神毫无变化，玩家的脑海里却响起自己刚才那句话——听起来突然可信极了。",
    narrativeConstraints: ["原催眠必须失败", "自我相信必须可纠正"],
    recoveryHooks: [hook({ kind: "cleanup", title: "分清真假", objective: "用证据把自己从谎言里拉出来", detail: "队友的一句话就能戳破，也可能戳不破。" })],
    absurdityScore: 4,
    longTermConsequenceScore: 2,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-disaster-catastrophic-omen",
    title: "占卜全错，唯一正确的部分指向玩家自己",
    families: ["divination"],
    primitives: ["REVEAL", "INFER"],
    polarity: "disaster",
    twist: "full-disaster",
    severity: 1,
    compatibleNormalResults: FAILURE_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("misplaced-target", "占卜结果几乎全错，唯一准确的部分指向玩家自己的办公室。"),
      effect("scene-absurdity", "所有错误答案在玩家办公室的桌上拼成了一个刺眼的符号。"),
    ],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：指向自己的预言", "占卜错得离谱，唯一准的部分是玩家自己的门牌。")],
    beliefProposals: [belief({ characterId: "player", subjectId: "self-omen", propositionKey: "fate:omen:self", claim: "这个符号与我有关", secrecy: "restricted" })],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [],
    narrativePremise: "纸上的答案全在胡说，只有最后一行的符号，和办公室门上的刻痕一模一样。",
    narrativeConstraints: ["原占卜必须失败", "指向必须可调查而非凭空诅咒"],
    recoveryHooks: [hook({ kind: "investigation", title: "查清符号", objective: "弄清符号为何出现在自己办公室", detail: "命运给了玩家一个必须正视的谜。" })],
    absurdityScore: 4,
    longTermConsequenceScore: 3,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-disaster-everyone-forgets",
    title: "所有痕迹消失，队友也忘记玩家在现场",
    families: ["concealment", "mental"],
    primitives: ["CONCEAL", "INFLUENCE"],
    polarity: "disaster",
    twist: "full-disaster",
    severity: 2,
    compatibleNormalResults: FAILURE_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("misplaced-audience", "隐匿彻底失败，却让所有痕迹消失，队友甚至忘记玩家当时在场。"),
      effect("misplaced-identity", "现场记录里没有玩家，任何证词都对不上。"),
    ],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：被抹去的人", "痕迹全部消失，队友却开始困惑‘你刚才在吗？’")],
    beliefProposals: [belief({ characterId: "teammate", subjectId: "player-presence", propositionKey: "fate:forget:presence", claim: "行动时玩家应该不在场", confidence: 0.8, secrecy: "restricted" })],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [plan({ title: "证明自己在场", objective: "让队友与记录重新认可玩家的参与", currentStep: "收集玩家在场但被抹掉的证据", ownerId: "player", participantIds: ["player"], secrecy: "secret" })],
    narrativePremise: "行动失败了，但更糟的是——队友们开始认真讨论，当时到底有没有你这个人。",
    narrativeConstraints: ["原隐匿必须失败", "记忆缺失必须可恢复"],
    recoveryHooks: [hook({ kind: "identity-claim", title: "重新证明存在", objective: "用物证或共同回忆把在场感找回来", detail: "被忘记的自己也是一种新身份。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 4,
    recoverabilityScore: 4,
  }),
  tpl({
    id: "fate-disaster-command-mixup",
    title: "命令被另一个目标接收并执行",
    families: ["control", "mental"],
    primitives: ["CONTROL", "INFLUENCE"],
    polarity: "disaster",
    twist: "full-disaster",
    severity: 1,
    compatibleNormalResults: FAILURE_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("misplaced-target", "控制失败，命令却被另一个毫不相干的人接收并严格执行。"),
      effect("organization-relation", "错接命令的人引来某方势力的追查。"),
    ],
    delayedEffects: [],
    worldEventProposals: [worldEvent("命运：命令接错人", "目标毫无反应，街对面的陌生人却开始执行命令。")],
    beliefProposals: [belief({ characterId: "wrong-target", subjectId: "player-command", propositionKey: "fate:command:wrong-target", claim: "这是上面下达的命令", confidence: 0.95, secrecy: "restricted" })],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [],
    narrativePremise: "目标没有中招，可街对面擦窗的工人忽然放下抹布，转身去做玩家刚想命令的事。",
    narrativeConstraints: ["原控制必须失败", "错接者必须带来可收拾的混乱"],
    recoveryHooks: [hook({ kind: "cleanup", title: "收回命令", objective: "在错接者闯祸前制止或利用他", detail: "他以为自己是奉命行事，这就很危险。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 3,
    recoverabilityScore: 3,
  }),
  tpl({
    id: "fate-disaster-ritual-debt",
    title: "仪式失败，却收到灵界正式回执与未知债务",
    families: ["ritual", "protection"],
    primitives: ["RITUAL_EFFECT", "PROTECT"],
    polarity: "disaster",
    twist: "full-disaster",
    severity: 3,
    compatibleNormalResults: FAILURE_SIDE,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [
      effect("new-debt", "仪式失败，玩家收到一张灵界正式回执，上面登记着一笔来历不明的债务。"),
      effect("long-term-belief", "回执被视为玩家欠灵界的书面凭据。"),
    ],
    delayedEffects: [delayed("debt-collector", 2, "new-debt", "回执登记的债主开始派使者上门。", "命运：灵界讨债")],
    worldEventProposals: [worldEvent("命运：灵界回执", "失败的仪式留下了一张正式回执——以及一笔债务。")],
    beliefProposals: [belief({ characterId: "spirit-debtor", subjectId: "player-debt", propositionKey: "fate:ritual:debt", claim: "此人欠灵界一笔债", confidence: 0.9, secrecy: "secret" })],
    relationshipProposals: [],
    commitmentProposals: [commitment({ type: "debt", participantIds: ["player", "spirit-creditor"], summary: "灵界回执登记的未知债务", secrecy: "secret" })],
    planProposals: [plan({ title: "查清灵界债务", objective: "弄清债务来源并决定偿还或抵赖", currentStep: "破译回执上的登记项", ownerId: "player", participantIds: ["player"], secrecy: "secret" })],
    narrativePremise: "仪式毫无反应，只有一张薄纸从烛火上飘落，上面写着玩家欠了什么——但字迹还在变化。",
    narrativeConstraints: ["原仪式必须失败", "债务必须可查清、可偿还或可转嫁"],
    recoveryHooks: [hook({ kind: "bargain", title: "与灵界讨价还价", objective: "弄清债务并选择偿还方式", detail: "债务本身也是一条接触灵界的通道。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 5,
    recoverabilityScore: 3,
  }),
  tpl({
    id: "fate-disaster-archival-causality",
    title: "官方档案发生大规模因果错误",
    families: ["ritual", "curse"],
    primitives: ["RITUAL_EFFECT", "RESOURCE_CHANGE", "BIND"],
    polarity: "disaster",
    twist: "full-disaster",
    severity: 4,
    compatibleNormalResults: FAILURE_SIDE,
    prerequisites: [cond("large-ritual"), cond("high-pressure")],
    forbiddenConditions: [],
    immediateEffects: [
      effect("authority-misplacement", "仪式失败引发的涟漪让城市官方档案发生大规模因果错误，组织被登记为多起事件的肇事方。"),
      effect("worldline-shift", "档案错误开始影响现实中的调查方向，世界线偏转。"),
    ],
    delayedEffects: [delayed("archive-audit", 2, "organization-relation", "官方开始按错误档案追查组织。", "命运：档案调查")],
    worldEventProposals: [worldEvent("命运：档案说谎", "一夜间，城市档案里出现了大量互相矛盾的因果记录。")],
    beliefProposals: [belief({ characterId: "clerk", subjectId: "org-blame", propositionKey: "fate:archive:blame", claim: "档案显示该组织牵涉多起事件", confidence: 0.9, secrecy: "restricted" })],
    relationshipProposals: [relationship({ fromCharacterId: "official", toCharacterId: "player", dimension: "suspicion", delta: 25, summary: "错误档案带来的官方怀疑" })],
    commitmentProposals: [],
    planProposals: [plan({ title: "纠正档案因果", objective: "让官方档案恢复正常或让组织掌握错误来源", currentStep: "定位被改写的档案条目", ownerId: "player", participantIds: ["player"], secrecy: "secret" })],
    narrativePremise: "第二天清晨，档案室里的记录像被无形的手重写过：组织名出现在所有错误的地方。",
    narrativeConstraints: ["必须写入世界线偏转记录", "档案错误必须可追溯、可纠正或可利用"],
    recoveryHooks: [hook({ kind: "identity-claim", title: "重写档案", objective: "纠正或利用官方的错误认知", detail: "错误档案既是危机，也是向官方渗透的入口。" })],
    absurdityScore: 5,
    longTermConsequenceScore: 5,
    recoverabilityScore: 3,
  }),
];

// ---------------------------------------------------------------- 确定性安全兜底
function fallbackTemplate(
  id: string,
  title: string,
  twist: FateTwist,
  polarity: "boon" | "disaster",
  compatible: ResultLevel[],
  premise: string
): FateAberrationTemplate {
  return tpl({
    id,
    title,
    families: ALL_FAMILIES,
    polarity,
    twist,
    severity: 1,
    compatibleNormalResults: compatible,
    prerequisites: [],
    forbiddenConditions: [],
    immediateEffects: [effect("scene-absurdity", "命运以最不起眼、最安全的方式完成了整蛊：一件小事变得极其离谱，但可以收场。")],
    delayedEffects: [],
    worldEventProposals: [worldEvent(`命运：${title}`, "命运打了个喷嚏，把玩家身边的一件小事吹歪了。")],
    beliefProposals: [],
    relationshipProposals: [],
    commitmentProposals: [],
    planProposals: [],
    narrativePremise: premise,
    narrativeConstraints: ["不得产生新的永久世界效果", "必须保留可继续经营的局面"],
    recoveryHooks: [hook({ kind: "cleanup", title: "收场", objective: "把被吹歪的小事拨回正轨", detail: "安全兜底只改变场景，不改变世界。" })],
    absurdityScore: 3,
    longTermConsequenceScore: 1,
    recoverabilityScore: 5,
  });
}

export const SAFE_FALLBACK_TEMPLATES: FateAberrationTemplate[] = [
  fallbackTemplate(
    "fate-safe-fallback-pure",
    "离谱但无伤大雅的额外收获",
    "pure",
    "boon",
    SUCCESS_SIDE,
    "目标完成了，桌上还多了一杯不知谁倒的茶——茶里浮着一片有用的纸条。"
  ),
  fallbackTemplate(
    "fate-safe-fallback-cursed-boon",
    "成功附带一场可以收场的误会",
    "cursed-boon",
    "disaster",
    SUCCESS_SIDE,
    "目标完成了，但门外正好有人听见了最关键的一句，并误会成了另一件事。"
  ),
  fallbackTemplate(
    "fate-safe-fallback-fortunate-disaster",
    "失败撞上一个可以收场的巧合",
    "fortunate-disaster",
    "boon",
    FAILURE_SIDE,
    "事情办砸了，可砸碎的东西下面，正好压着一条有用的线索。"
  ),
  fallbackTemplate(
    "fate-safe-fallback-full-disaster",
    "全面失控但局面仍可收拾",
    "full-disaster",
    "disaster",
    FAILURE_SIDE,
    "事情彻底歪了，但歪出来的局面还有一张牌可以打。"
  ),
];

export function fateTemplates(): FateAberrationTemplate[] {
  return FATE_TEMPLATES;
}

export function safeFallbackFor(twist: FateTwist): FateAberrationTemplate {
  const map: Record<FateTwist, FateAberrationTemplate | undefined> = {
    pure: SAFE_FALLBACK_TEMPLATES.find((item) => item.id === "fate-safe-fallback-pure"),
    "cursed-boon": SAFE_FALLBACK_TEMPLATES.find((item) => item.id === "fate-safe-fallback-cursed-boon"),
    "fortunate-disaster": SAFE_FALLBACK_TEMPLATES.find((item) => item.id === "fate-safe-fallback-fortunate-disaster"),
    "full-disaster": SAFE_FALLBACK_TEMPLATES.find((item) => item.id === "fate-safe-fallback-full-disaster"),
  };
  const template = map[twist];
  if (!template) throw new Error(`缺少安全兜底模板：${twist}`);
  return template;
}
